services:
  backend:
    build: ./backend
    container_name: novameet-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    restart: always

  frontend:
    build: ./frontend
    container_name: novameet-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always




  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3001"

  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
    network_mode: "host"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

